const URLS = {
  HOST_URL: 'https://superadmin.mandreducation.in',
  SUFFIX_URL: '/api/v1',
  LOGIN: `/login`,
  LOG_OUT: `/logout`,
  GET_PROFILE: '/profile',
  UPDATE_PROFILE: '/profile/update',
  CHANGE_PASSWORD: '/change-password',
  FORGOT_PASSWORD: '/password/email',
  RESET_PASSWORD: token => `/password/reset?token=${token}`,
  DASHBOARD: () => `/organisations/dashboard`,
  ADD_PLAN: () => `/plans`,
  GET_PLAN: () => `/plans`,
  EDIT_PLAN: id => `/plans/${id}`,
  UPDATE_PLAN: id => `/plans/${id}`,
  DELETE_PLAN: id => `/plans/${id}`,
  ADD_ADMIN: () => `/admins`,
  GET_ADMINS: () => `/admins`,
  EDIT_ADMIN: id => `/admins/${id}`,
  UPDATE_ADMIN: id => `/admins/${id}`,
  DELETE_ADMIN: id => `/admins/${id}`,
  ADD_FEATURE: () => `/features`,
  GET_FEATURES: () => `/features`,
  EDIT_FEATURE: id => `/features/${id}`,
  UPDATE_FEATURE: id => `/features/${id}`,
  DELETE_FEATURE: id => `/features/${id}`,
  ADD_QUESTION_BANK: () => `/questionbanks`,
  GET_QUESTION_BANK: () => `/questionbanks`,
  EDIT_QUESTION_BANK: id => `/questionbanks/${id}`,
  UPDATE_QUESTION_BANK: id => `/questionbanks/${id}`,
  DELETE_QUESTION_BANK: id => `/questionbanks/${id}`,
  ADD_COURSE: () => `/courses`,
  GET_COURSE: (searchInput, pageSize) =>
    `/courses?search=${searchInput}&page_size=${pageSize}`,
  GET_COURSE_LIST: '/courses',
  EDIT_COURSE: id => `/courses/${id}`,
  DELETE_COURSE: id => `/courses/${id}`,
  ADD_SUBJECT: () => `/subjects`,
  GET_SUBJECT: (searchInput, pageSize, courseId) =>
    `/subjects?search=${searchInput}&page_size=${pageSize}&course_id=${courseId}`,
  GET_SUBJECT_LIST: '/subjects',
  SUBJECT_BY_ID: id => `/subjects/${id}`,
  UPDATE_SUBJECT: id => `/subjects/${id}`,
  DELETE_SUBJECT: id => `/subjects/${id}`,
  ADD_CHAPTER: () => `/chapters`,
  GET_CHAPTER: (searchInput, pageSize, courseId, subjectId) =>
    `/chapters?search=${searchInput}&page_size=${pageSize}&course_id=${courseId}&subject_id=${subjectId}`,
  GET_CHAPTER_LIST: '/chapters',
  CHAPTER_BY_ID: id => `/chapters/${id}`,
  UPDATE_CHAPTER: id => `/chapters/${id}`,
  DELETE_CHAPTER: id => `/chapters/${id}`,
  GET_CONTENT: (searchInput, pageSize) =>
    `/materials?search=${searchInput}&page=${pageSize}`,
  ADD_CONTENT: () => `/materials`,
  CONTENT_BY_ID: id => `/materials/${id}`,
  CONTENT_LOCKED: id => `/materials/islocked/${id}`,
  ADD_LANGUAGES: () => `/languages`,
  GET_LANGUAGES: () => `/languages`,
  EDIT_LANGUAGES: id => `/languages/${id}`,
  UPDATE_LANGUAGES: id => `/languages/${id}`,
  DELETE_LANGUAGES: id => `/languages/${id}`,
  ADD_ACADEMIC_YEAR: () => `/academic-years`,
  GET_ACADEMIC_YEAR: () => `/academic-years`,
  EDIT_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  UPDATE_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  DELETE_ACADEMIC_YEAR: id => `/academic-years/${id}`,
  GET_NOTIFICATION: (searchInput, pageSize) =>
    `/notifications?search=${searchInput}&page_size=${pageSize}`,
  ADD_NOTIFICATION: () => `/notifications`,
  EDIT_NOTIFICATION: id => `/notifications/${id}`,
  DELETE_NOTIFICATION: id => `/notifications/${id}`,
  GET_STAFF: () => `/staff`,
  GET_STAFF_By_Id: id => `/staff/${id}`,
  ADD_STAFF: () => `/staff`,
  UPDATE_STAFF: id => `/staff/${id}`,
  DELETE_STAFF: id => `/staff/${id}`,
  GET_BANNER: () => `/banners`,
  ADD_BANNER: () => `/banners`,
  EDIT_BANNER: id => `/banners/${id}`,
  UPDATE_BANNER: id => `/banners/${id}`,
  DELETE_BANNER: id => `/banners/${id}`,
  GET_ANNOUNCEMENT: () => `/announcements`,
  ADD_ANNOUNCEMENT: () => `/announcements`,
  EDIT_ANNOUNCEMENT: id => `/announcements/${id}`,
  DELETE_ANNOUNCEMENT: id => `/announcements/${id}`,
  GET_EVENT: () => `/events`,
  GET_STATES: '/states',
  GET_CITIES: '/cities',
  EVENTS: '/events',
};
export default URLS;
